### ISSUE TITLE
Notes from Brainstorm Session

### ISSUE THREAD

**Issue by nargolg1** [nargolg1/PhD-Shelter-Shrub-Climate#1]
1. What progress have you made directly on PhD research since July?
Microclimate data is up. Loggers are tidy and up. I'm almost done with the greenhouse paper and want to send that to Chris
withing the next week or so we can submit it to the Journal of Materials and Environmental Science. Processed some camtraps.
Meta is still under review.

2. What field data do you have from last year? loggers and cams? Loggers published. Any other data assets from the field?
Loggers, cams, and microclimate. 

3. What is your plan for this upcoming year?
Repeat experiment at two regional sites again with the same fabric if it is a wet year if not test a different fabric. Use sandbag to glue to the gronund.
Get someone to process the rest of the camtraps. 
Analyze the shelter logger data and write paper.  

IDEAS

4. How could innovate, augment, extend what you propose through techs, teaching release if you want me to write letter, other data, or sampling more widely.  Dream here.
Go in February for two weeks and sample the gradient. Take 20 shrubs at panoche, cuyama, carrizo, and mojave and sample microclimate and write a paper about that. 
Or do that with loggers but have to get a tech because it's unrealistic to drive that much in the first week.
or instead compare between handhelds and logger data. We already have all the shrub sizes.

-look at species home ranges and double-check with camtraps
-draw a map of where the shelters were
-draw a polygon around them and calculate the distance
-one day of camtraps and make a species list- pilot scrape 
-run the handheld data stuff (Maybe get someone to do this for an entire month or two)
-Calculate distance for camtraps from each other
-systematic placement of camtraps relative to shrubs or other land features (i.e grid, transect etc.)
-How many shelters/area?
-Does the proximity of shrubs matter? If yes, what sizes?

**Comment by zenrabbit** [comment]
aces!!! Maybe do a very, very rapid did through peer-review lit on thermal refuges in deserts, meta-pop, and spatial arrangement etc. see if there are optimal distances etc for diff animals reported.

**Comment by zenrabbit** [comment]
Ethan has also looked up all home range sizes for all herps in the region too - so can use later too.

**Comment by zenrabbit** [comment]
- add a folder for data
- add a folder for key pdfs
- put 2022 data in here and a link to the EDI published version in the 'readme'
-

**Comment by zenrabbit** [comment]
actually is this repo for all PhD?
I see Owen and cognates etc

spin up to two new repos I think

1. shelter microclimate study
2. shrub size and point temperature experiment
